azure:
  service-bus:
    connection-string: sensitive_set_get_from_env_var
endpoints:
  enabled: true
  sensitive: false
info:
  java:
    source: "${java.version}"
logging:
  level:
    root: INFO
management:
  info:
    build:
      enabled: true
    git:
      mode: full
server:
  port: 8097
  context-path: /candidate
spring:
  application:
    name: Candidate Service
  data:
    mongodb:
      database: candidates
      host: localhost
      port: 27017
---
server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongodb
  profiles: docker-local
---
endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true
  sensitive: true
logging:
  level:
    root: WARN
management:
  info:
    build:
      enabled: false
    git:
      enabled: false
server:
  port: 8080
spring:
  data:
    mongodb:
      host: "10.0.1.6"
  profiles: aws-production
---
server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongodb
  profiles: docker-aks
---
endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true
  sensitive: true
logging:
  level:
    root: WARN
management:
  info:
    build:
      enabled: false
    git:
      enabled: false
server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongodb
  profiles: docker-production
